# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Develop
- qa
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd server
    npm install
  displayName: 'npm install'

- script: |
    cd server
    npm install jest --save-dev
  displayName: 'Install Jest'

- script: |
    cd server
    rm -rf node_modules package-lock.json
    npm install --build-from-source bcrypt
  displayName: 'Clean and reinstall dependencies'
  
- script: |
    cd client
    npm install
  displayName: 'npm install'

# Arreglando permisos de la dependencia del servidor del cliente
- script: |
    chmod +x ./node_modules/.bin/web-dev-server
  workingDirectory: $(System.DefaultWorkingDirectory)/client
  displayName: 'Fix permissions for web-dev-server'
  
  # build the server
- script: |
    cd server
    npm run dev
  displayName: 'npm build-server'

- script: |
    cd server
    npm test
  displayName: run 'Tests'
  
  # build the client
- script: |
    cd client
    npm start
  displayName: 'npm build-client'

  # Package server and client for deployment
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'server'
    ArtifactName: 'server-drop'
    publishLocation: 'Container'
  displayName: 'Publish server artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'client'
    ArtifactName: 'client-drop'
    publishLocation: 'Container'
  displayName: 'Publish client artifacts'